### PR TITLE
[15.0][IMP] mrp_project: remove restriction project sequence

### PR DESCRIPTION
**Pull request by IriaAlonso**
Remove restriction project secuence

### CODE REVIEW

**Comment by IriaAlonso** [comment]
@dalonsod can you review this?

**Comment by dalonsod** [comment]
OK, only three minor things:
* Fix typo for commit title _secuence_ => sequence.
* Add yourself as contributor.
* Re-create `i18n` files, as removed code had translatable strings.

Once done, I'll test it ASAP

**Comment by IriaAlonso** [comment]
@dalonsod changes made

**Comment by dalonsod** [comment]
@ChristianSantamaria could you install this IMP, if possible, in CrtTest environment?

**Comment by ChristianSantamaria** [comment]
@dalonsod Updated :+1:

**Review by dalonsod — APPROVED** [review]
:+1:

**Pull request merged**
