### PR TITLE
[13.0][FIX] mrp_unbuild_cust_alu_analytics: Some fixes on XLSX reports, refactoring and fix error on unbuild view

### PR DESCRIPTION
**Pull request by adriresu**

### CODE REVIEW

**Comment by dalonsod** [comment]
Hello @adriresu I see four different commits. Please let us know how many new IMP and/or FIX are exactly included at this time, and change PR title if needed,as I don't know if it's real or simply initial purpose and doesn't help other contributors.

We should make single-funcionality PRs if possible. But if not, their names and complete list of new additions should be clear for all.

cc @ChristianSantamaria

**Comment by adriresu** [comment]
Hi,
This changes involve some fixes on reports, fix on ubuild view to prevent error when selecting a product and commented code.

**Comment by dalonsod** [comment]
@ChristianSantamaria could you check this up-to-date with main branch? There are two new commits, and one of them is suspicious...

**Comment by dalonsod** [comment]
Let's merge it!

**Pull request merged**
